#!/usr/bin/bash

[ -z "$MOZ_DISABLE_WAYLAND" ] && { [ "$XDG_CURRENT_DESKTOP" == "GNOME" ] && [ -n "$WAYLAND_DISPLAY" ] || [ "$XDG_SESSION_TYPE" == "wayland" ]; } && export MOZ_ENABLE_WAYLAND=1 && export MOZ_DBUS_REMOTE=1

export MOZ_APP_LAUNCHER="$0"

exec /opt/firefox-dev/firefox "$@"
